### ISSUE TITLE
error when trying to install Podfile

### ISSUE THREAD

**Issue by luizParreira** [Masonry/Masonry#147]
### Report

* What did you do?
I tried to install this podfile, at first it said that the reason that it was not working was that I was not using the latest version of cocoa pods, but I have updated it and still gives me an error.

* What did you expect to happen?
I expected to have this 'Masonry' pod installed.

* What happened instead?
error

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a28d01d6b6047877cb94e179e2296b736ed20468
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
pod 'Firebase', '>= 2.1.0’
pod ‘Masonry’
```

### Error

```
SyntaxError - /Users/luizparreira/blocWork/PerguntaAe/Podfile:1: unterminated string meets end of file
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:220:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:108:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by kouky** [comment]
@luizParreira can you double check the quotes in your Podfile, they need to be single quotes. Your podfile text causes errors for me too.

Make it
```
pod 'Masonry'
```

**Comment by luizParreira** [comment]
@kouky I have tried so and still gives me the same error:

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a28d01d6b6047877cb94e179e2296b736ed20468
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
pod 'Firebase', '>= 2.1.0’
pod 'Masonry'
```

### Error

```
SyntaxError - /Users/luizparreira/blocWork/PerguntaAe/Podfile:2: syntax error, unexpected tCONSTANT, expecting end-of-input
pod 'Masonry'
            ^
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:220:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:108:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by kouky** [comment]
@luizParreira your Podfile still has an incorrect single quote on the first line following the version number for Firebase.

Update your  Podfile to this and it should work.

```
pod 'Firebase', '>= 2.1.0'
pod 'Masonry'
```

**Comment by luizParreira** [comment]
@kouky Oh, finally. Thanks man, it worked now. :)

**Comment by kouky** [comment]
@luizParreira :+1:
